### ISSUE TITLE
Can't see csv-file for import

### ISSUE THREAD

**Issue by ThomasStruller** [Scriptbash/PluginExporter#2]
Hallo,
I am on 

QGIS-Version | 3.36.2-Maidenhead | QGIS-Codeversion | 30c61a14b67
Qt-Version | 5.15.3
Python-Version | 3.10.12

BS-Version
Linux Mint 21.3

tried to import plugins with a csv file. Was scrolling to my directory but I can't see it in your dialog box for importing a csv-file.

![grafik](https://github.com/Scriptbash/PluginExporter/assets/53342765/82ca63ee-cfdc-4677-9917-ae97677036c7)

but my import-csv file is in this directory. 
Look here:
![grafik](https://github.com/Scriptbash/PluginExporter/assets/53342765/72c8cb42-8573-4a29-aab5-90d43e5a0743)

**Comment by Scriptbash** [comment]
Hi Thomas, thank you very much for reporting this issue! The problem should be fixed in the new release I just published. I will submit the update to the QGIS repo, in the meantime you can install the plugin using the zip file [here](https://github.com/Scriptbash/PluginExporter/releases/download/v0.2.1/plugin_exporter.zip). I will close this issue for now, but if the update didn't work for you, we can reopen it. Thanks again :)

**Comment by ThomasStruller** [comment]
Thank you 🙂

Am Mittwoch, dem 01.05.2024 um 08:02 -0700 schrieb Francis Lapointe:
